package com.flechazo.apisentinel.util;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Standalone multi-dimension Bambda generator — a Java port of Bambda++'s
 * {@code build_code}. Produces a Bambda for Burp's Proxy HTTP-history filter
 * from a {@link BambdaFilterSettings} snapshot (method / domain / keywords /
 * MIME / status / search / extension / annotation / listener).
 *
 * <p>Output assumes Burp's Bambda editor context (a {@code requestResponse}
 * variable, auto-imported {@code java.util.*} / {@code java.util.regex.*} and
 * Montoya types) — identical to the original plugin's assumptions.
 */
public final class BambdaBuilder {

    private BambdaBuilder() {}

    public static String build(BambdaFilterSettings s) {
        List<String> methods = s.filterMethodEnabled ? dedup(s.methods) : List.of();
        List<String> domainExcludes = s.filterDomainEnabled ? dedupSplitLower(s.domains) : List.of();
        List<String> keywords = s.filterKeywordsEnabled ? dedupSplit(s.keywords) : List.of();
        List<String> excludeKeywords = s.filterExcludeKeywordsEnabled ? dedupSplit(s.excludeKeywords) : List.of();

        List<String> showOnlyExts = s.showOnlyExtEnabled ? dedupSplitLower(s.showOnlyExt) : List.of();
        List<String> hideExts = (s.hideExtEnabled && showOnlyExts.isEmpty()) ? dedupSplitLower(s.hideExt) : List.of();

        String searchTerm = s.searchTerm == null ? "" : s.searchTerm.trim();
        boolean searchEnabled = s.searchFilterEnabled && !searchTerm.isEmpty();

        boolean mimeFilterEnabled = s.mimeTypes != null && !s.mimeTypes.isEmpty()
                && s.mimeTypes.size() != BambdaFilterSettings.ALL_MIME.size();
        boolean statusFilterEnabled = s.statusCodes != null && !s.statusCodes.isEmpty()
                && s.statusCodes.size() != BambdaFilterSettings.ALL_STATUS.size();

        boolean hasResponseRequired = s.filterHasResponse || mimeFilterEnabled || statusFilterEnabled || searchEnabled;

        StringBuilder c = new StringBuilder();
        c.append("// Auto-generated by API Sentinel — paste into Burp Proxy > HTTP history > Bambda\n");

        if (hasResponseRequired) {
            c.append("boolean hasResponse = requestResponse.response() != null;\n");
        }
        if (s.filterParameterized) {
            // Montoya's Bambda context exposes a real HttpRequest — no reflection/try-catch needed.
            c.append("boolean hasParameters = !requestResponse.request().parameters().isEmpty();\n");
        }
        if (s.filterInScope) {
            c.append("boolean inScope = requestResponse.request().isInScope();\n");
        }
        if (!methods.isEmpty()) {
            c.append("String[] methodExclude = {").append(joinQuoted(methods)).append("};\n");
            c.append("String method = requestResponse.request().method();\n");
            c.append("boolean methodExcluded = false;\n");
            c.append("for (String m : methodExclude) { if (method.contains(m)) { methodExcluded = true; break; } }\n");
        }
        if (!domainExcludes.isEmpty()) {
            List<String> pats = new ArrayList<>();
            for (String d : domainExcludes) pats.add(escapeRegexKeepWildcard(d));
            c.append("Pattern[] domainExclude = {").append(joinPatternCompile(pats, true)).append("};\n");
            c.append("String host = requestResponse.request().httpService().host().toLowerCase();\n");
            c.append("boolean isExcludedDomain = false;\n");
            c.append("for (Pattern p : domainExclude) { if (p.matcher(host).find()) { isExcludedDomain = true; break; } }\n");
        }
        boolean requestContentNeeded = !keywords.isEmpty() || !excludeKeywords.isEmpty();
        if (requestContentNeeded) {
            c.append("String requestContent = requestResponse.request().toString();\n");
        }
        if (mimeFilterEnabled) {
            c.append("String contentType = \"\";\n");
            c.append("if (hasResponse) {\n");
            c.append("    String ct = requestResponse.response().headerValue(\"Content-Type\");\n");
            c.append("    contentType = ct == null ? \"\" : ct.toLowerCase();\n");
            c.append("}\n");
            c.append("String mimeTag = \"Other binary\";\n");
            c.append("if (contentType.contains(\"html\")) { mimeTag = \"HTML\"; }\n");
            c.append("else if (contentType.contains(\"javascript\") || contentType.contains(\"ecmascript\")) { mimeTag = \"Script\"; }\n");
            c.append("else if (contentType.contains(\"xml\")) { mimeTag = \"XML\"; }\n");
            c.append("else if (contentType.contains(\"css\")) { mimeTag = \"CSS\"; }\n");
            c.append("else if (contentType.startsWith(\"text/\") || contentType.contains(\"json\")) { mimeTag = \"Other text\"; }\n");
            c.append("else if (contentType.contains(\"image\")) { mimeTag = \"Images\"; }\n");
            c.append("else if (contentType.contains(\"flash\")) { mimeTag = \"Flash\"; }\n");
            c.append("String[] allowedMime = {").append(joinQuoted(s.mimeTypes)).append("};\n");
            c.append("boolean mimeAllowed = false;\n");
            c.append("for (String m : allowedMime) { if (m.equals(mimeTag)) { mimeAllowed = true; break; } }\n");
        }
        if (statusFilterEnabled) {
            c.append("int statusCode = hasResponse ? requestResponse.response().statusCode() : -1;\n");
            c.append("boolean statusAllowed = false;\n");
            c.append("if (statusCode >= 200 && statusCode < 300) { statusAllowed = ")
             .append(contains(s.statusCodes, "2xx [success]")).append("; }\n");
            c.append("else if (statusCode >= 300 && statusCode < 400) { statusAllowed = ")
             .append(contains(s.statusCodes, "3xx [redirection]")).append("; }\n");
            c.append("else if (statusCode >= 400 && statusCode < 500) { statusAllowed = ")
             .append(contains(s.statusCodes, "4xx [request error]")).append("; }\n");
            c.append("else if (statusCode >= 500 && statusCode < 600) { statusAllowed = ")
             .append(contains(s.statusCodes, "5xx [server error]")).append("; }\n");
        }
        String searchMatchVar = null;
        if (searchEnabled) {
            c.append("String searchHaystack = requestResponse.request().toString();\n");
            c.append("if (hasResponse) { searchHaystack += \"\\n\" + requestResponse.response().toString(); }\n");
            if (!s.searchRegex) {
                c.append("Pattern searchPattern = Pattern.compile(Pattern.quote(\"")
                 .append(escapeJava(searchTerm)).append("\")")
                 .append(s.searchCaseSensitive ? "" : ", Pattern.CASE_INSENSITIVE").append(");\n");
            } else {
                c.append("Pattern searchPattern = Pattern.compile(\"")
                 .append(escapeJava(searchTerm)).append("\", ")
                 .append(s.searchCaseSensitive ? "0" : "Pattern.CASE_INSENSITIVE").append(");\n");
            }
            c.append("boolean searchMatched = searchPattern.matcher(searchHaystack).find();\n");
            searchMatchVar = s.searchNegative ? "!searchMatched" : "searchMatched";
        }
        if (!keywords.isEmpty()) {
            List<String> pats = new ArrayList<>();
            for (String k : keywords) pats.add(escapeRegexKeepWildcard(k));
            c.append("Pattern[] keywordPatterns = {").append(joinPatternCompile(pats, false)).append("};\n");
            c.append("boolean containsAnyKeyword = false;\n");
            c.append("for (Pattern p : keywordPatterns) { if (p.matcher(requestContent).find()) { containsAnyKeyword = true; break; } }\n");
        }
        if (!excludeKeywords.isEmpty()) {
            List<String> pats = new ArrayList<>();
            for (String k : excludeKeywords) pats.add(escapeRegexKeepWildcard(k));
            c.append("Pattern[] excludeKeywordPatterns = {").append(joinPatternCompile(pats, false)).append("};\n");
            c.append("boolean containsExcludeKeyword = false;\n");
            c.append("for (Pattern p : excludeKeywordPatterns) { if (p.matcher(requestContent).find()) { containsExcludeKeyword = true; break; } }\n");
        }
        boolean needPath = !showOnlyExts.isEmpty() || !hideExts.isEmpty();
        if (needPath) {
            c.append("String path = requestResponse.request().pathWithoutQuery().toLowerCase();\n");
        }
        if (s.highlightEnabled) {
            c.append("boolean hasHighlight = requestResponse.annotations().hasHighlightColor();\n");
        }
        if (!showOnlyExts.isEmpty()) {
            c.append("String[] showExtOnly = {").append(joinQuoted(showOnlyExts)).append("};\n");
            c.append("boolean matchShowExt = false;\n");
            c.append("for (String e : showExtOnly) { if (path.endsWith(e)) { matchShowExt = true; break; } }\n");
        }
        if (!hideExts.isEmpty()) {
            c.append("String[] hideExtList = {").append(joinQuoted(hideExts)).append("};\n");
            c.append("boolean matchHideExt = false;\n");
            c.append("for (String e : hideExtList) { if (path.endsWith(e)) { matchHideExt = true; break; } }\n");
        }
        if (s.filterNotesOnly) {
            c.append("String notes = requestResponse.annotations().notes();\n");
            c.append("boolean hasNotes = notes != null && !notes.isEmpty();\n");
        }
        boolean portFilter = s.listenerPort != null && s.listenerPort.matches("\\d+");
        if (portFilter) {
            c.append("int listenerPort = requestResponse.request().httpService().port();\n");
            c.append("boolean matchPort = listenerPort == ").append(s.listenerPort).append(";\n");
        }

        List<String> conditions = new ArrayList<>();
        if (hasResponseRequired) conditions.add("hasResponse");
        if (s.filterInScope) conditions.add("inScope");
        if (portFilter) conditions.add("matchPort");
        if (!methods.isEmpty()) conditions.add("!methodExcluded");
        if (s.filterParameterized) conditions.add("hasParameters");
        if (!domainExcludes.isEmpty()) conditions.add("!isExcludedDomain");
        if (!showOnlyExts.isEmpty()) conditions.add("matchShowExt");
        if (!hideExts.isEmpty()) conditions.add("!matchHideExt");
        if (mimeFilterEnabled) conditions.add("mimeAllowed");
        if (statusFilterEnabled) conditions.add("statusAllowed");
        if (!keywords.isEmpty()) conditions.add("containsAnyKeyword");
        if (!excludeKeywords.isEmpty()) conditions.add("!containsExcludeKeyword");
        if (searchMatchVar != null) conditions.add(searchMatchVar);
        if (s.highlightEnabled) conditions.add("hasHighlight");
        if (s.filterNotesOnly) conditions.add("hasNotes");

        if (conditions.isEmpty()) {
            c.append("return true;\n");
        } else {
            c.append("return ").append(String.join(" && ", conditions)).append(";\n");
        }
        return c.toString();
    }

    // ======================== helpers ========================

    private static List<String> dedup(List<String> items) {
        Set<String> seen = new LinkedHashSet<>();
        for (String it : items) {
            if (it == null) continue;
            String t = it.trim();
            if (!t.isEmpty()) seen.add(t);
        }
        return new ArrayList<>(seen);
    }

    private static List<String> dedupSplit(String csv) {
        return dedup(csv == null ? List.of() : Arrays.asList(csv.split(",")));
    }

    private static List<String> dedupSplitLower(String csv) {
        List<String> out = new ArrayList<>();
        for (String it : dedupSplit(csv)) out.add(it.toLowerCase());
        return dedup(out);
    }

    /** Emit {@code Pattern.compile("p"[, CASE_INSENSITIVE]), ...} so patterns are
     *  compiled ONCE (hoisted out of the per-request stream), not on every match. */
    private static String joinPatternCompile(List<String> patterns, boolean caseInsensitive) {
        String flag = caseInsensitive ? ", Pattern.CASE_INSENSITIVE" : "";
        List<String> q = new ArrayList<>();
        for (String p : patterns) q.add("Pattern.compile(\"" + escapeJava(p) + "\"" + flag + ")");
        return String.join(", ", q);
    }

    private static String joinQuoted(List<String> items) {
        List<String> q = new ArrayList<>();
        for (String it : items) q.add("\"" + escapeJava(it) + "\"");
        return String.join(", ", q);
    }

    private static String contains(List<String> list, String v) {
        return String.valueOf(list != null && list.contains(v));
    }

    /** Regex-escape literal text but turn {@code *} into {@code .*} (wildcard). */
    static String escapeRegexKeepWildcard(String s) {
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char ch = s.charAt(i);
            if (ch == '*') {
                out.append(".*");
            } else if ("\\.[]{}()<>+-=!?^$|".indexOf(ch) >= 0) {
                out.append('\\').append(ch);
            } else {
                out.append(ch);
            }
        }
        return out.toString();
    }

    private static String escapeJava(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r");
    }
}
