package com.flechazo.apisentinel.util;

import com.flechazo.apisentinel.model.ApiEntry;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates Bambda expressions for Burp Suite's Proxy HTTP-history filter from
 * captured API entries. Paste the output straight into Burp's native Bambda
 * editor (which auto-imports {@code java.util.*}, {@code java.util.regex.*} and
 * the Montoya types used below).
 *
 * <p>Stronger than a naive {@code url().contains(path)}:
 * <ul>
 *   <li><b>Templated paths</b> — {@code /api/users/{id}} or {@code /a/*} become a
 *       real regex ({@code /api/users/[^/]+}) so they actually match live URLs.
 *       (Plain {@code contains("/api/users/{id}")} never matches {@code /api/users/123}.)</li>
 *   <li><b>Precise matching</b> — exact host ({@code httpService().host()}),
 *       exact method, and path compared against {@code pathWithoutQuery()} rather
 *       than a substring of the whole URL.</li>
 *   <li><b>Modes</b> — {@link Mode#FILTER show}, {@link Mode#EXCLUDE hide} or
 *       {@link Mode#HIGHLIGHT colour} the matching requests.</li>
 * </ul>
 */
public class BambdaCodeGen {

    /** What the generated Bambda does with matching requests. */
    public enum Mode { FILTER, EXCLUDE, HIGHLIGHT }

    public static String generate(ApiEntry entry) {
        return generateBatch(List.of(entry), Mode.FILTER);
    }

    public static String generate(ApiEntry entry, Mode mode) {
        return generateBatch(List.of(entry), mode);
    }

    public static String generateBatch(List<ApiEntry> entries) {
        return generateBatch(entries, Mode.FILTER);
    }

    /**
     * Generate a Bambda for the given entries, OR-combined and grouped by domain.
     */
    public static String generateBatch(List<ApiEntry> entries, Mode mode) {
        if (entries == null || entries.isEmpty()) {
            return "// No APIs selected\nreturn false;";
        }
        if (mode == null) mode = Mode.FILTER;

        // Group entries by domain so a shared host check is factored out per group.
        // Entries with no domain fall back to the most common domain from the
        // others (so they still get a host check instead of matching any host).
        Map<String, List<ApiEntry>> byDomain = new LinkedHashMap<>();
        String mostCommonDomain = "";
        int mostCommonCount = 0;
        for (ApiEntry e : entries) {
            String d = e.getDomain() == null ? "" : e.getDomain();
            if (!d.isEmpty() && (byDomain.getOrDefault(d, List.of()).size() + 1) > mostCommonCount) {
                mostCommonDomain = d;
                mostCommonCount = byDomain.getOrDefault(d, List.of()).size() + 1;
            }
            byDomain.computeIfAbsent(d, k -> new ArrayList<>()).add(e);
        }
        // Merge empty-domain entries into the most common domain group.
        if (!mostCommonDomain.isEmpty() && byDomain.containsKey("")) {
            byDomain.get(mostCommonDomain).addAll(byDomain.remove(""));
        }

        List<String> patternDecls = new ArrayList<>();   // Pattern pN = Pattern.compile(...);
        List<String> groupExprs = new ArrayList<>();      // one OR-group per domain
        int[] patternCounter = {0};
        boolean[] usesMethod = {false};

        for (Map.Entry<String, List<ApiEntry>> g : byDomain.entrySet()) {
            String domain = g.getKey();
            List<String> pathConds = new ArrayList<>();
            for (ApiEntry e : g.getValue()) {
                pathConds.add(entryCondition(e, patternDecls, patternCounter, usesMethod));
            }
            String paths = pathConds.size() == 1
                    ? pathConds.get(0)
                    : "(" + String.join("\n         || ", pathConds) + ")";

            if (domain != null && !domain.isEmpty()) {
                groupExprs.add("(reqHost.equalsIgnoreCase(\"" + escapeJava(domain) + "\") && " + paths + ")");
            } else {
                groupExprs.add(paths);
            }
        }

        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by API Sentinel — ").append(entries.size())
          .append(" API(s), mode=").append(mode).append("\n");
        sb.append("String reqHost = requestResponse.request().httpService().host();\n");
        sb.append("String reqPath = requestResponse.request().pathWithoutQuery();\n");
        sb.append("String reqUrl = requestResponse.request().url().toLowerCase();\n");
        for (String decl : patternDecls) sb.append(decl).append("\n");

        sb.append("boolean matched =\n    ")
          .append(String.join("\n    || ", groupExprs))
          .append(";\n");

        switch (mode) {
            case EXCLUDE -> sb.append("return !matched;");
            case HIGHLIGHT -> sb.append("if (matched) "
                    + "requestResponse.annotations().setHighlightColor(HighlightColor.RED);\n"
                    + "return true;");
            default -> sb.append("return matched;");
        }
        return sb.toString();
    }

    /** Build the path condition for one entry.
     *  - Normal REST paths (start with /): match against pathWithoutQuery()
     *    (equals for exact, regex for templated {id}/*). Precise, no false positives.
     *  - RPC action names (no leading /): match against url().contains() —
     *    the action lives in the query string (?InnerAction=GetX), not the path.
     *  No method check per user request. */
    private static String entryCondition(ApiEntry e, List<String> patternDecls,
                                          int[] patternCounter, boolean[] usesMethod) {
        String path = e.getApiPath() == null ? "" : e.getApiPath();

        // RPC gateway style: action name without a leading /.
        if (!path.startsWith("/")) {
            String lc = escapeJava(path.toLowerCase(java.util.Locale.ROOT));
            return "reqUrl.contains(\"" + lc + "\")";
        }

        // Normal REST path: match against pathWithoutQuery() for precision.
        if (isTemplated(path)) {
            String regex = pathToRegex(path);
            String var = "p" + (patternCounter[0]++);
            patternDecls.add("Pattern " + var + " = Pattern.compile(\"" + escapeJava(regex) + "\");");
            return var + ".matcher(reqPath).matches()";
        } else {
            return "reqPath.equals(\"" + escapeJava(path) + "\")";
        }
    }

    /** A path is templated when it carries a {placeholder} or a * wildcard. */
    private static boolean isTemplated(String path) {
        return path.indexOf('{') >= 0 || path.indexOf('*') >= 0;
    }

    /**
     * Convert a templated API path into an anchored regex:
     * {@code {id}} → {@code [^/]+}, {@code *} → {@code .*}, everything else is
     * regex-escaped so it matches literally.
     */
    static String pathToRegex(String path) {
        StringBuilder re = new StringBuilder("^");
        int i = 0;
        while (i < path.length()) {
            char c = path.charAt(i);
            if (c == '{') {
                int end = path.indexOf('}', i);
                if (end > i) {           // {id} → one path segment
                    re.append("[^/]+");
                    i = end + 1;
                    continue;
                }
            }
            if (c == '*') {              // wildcard → any run
                re.append(".*");
                i++;
                continue;
            }
            re.append(quoteRegexChar(c));
            i++;
        }
        re.append("$");
        return re.toString();
    }

    /** Escape a single char for use in a regex literal. */
    private static String quoteRegexChar(char c) {
        if ("\\.[]{}()<>*+-=!?^$|".indexOf(c) >= 0) {
            return "\\" + c;
        }
        return String.valueOf(c);
    }

    /** Escape a string for embedding inside a Java string literal. */
    private static String escapeJava(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }
}
