package com.flechazo.apisentinel.util;

import com.flechazo.apisentinel.model.ApiEntry;

import java.util.List;

/**
 * Generates Bambda filter expressions for Burp Suite's Proxy History filter.
 * Users can copy the generated code and paste it into Burp's native Bambda editor.
 */
public class BambdaCodeGen {

    /**
     * Generate a Bambda filter expression for a single API entry.
     */
    public static String generate(ApiEntry entry) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by API Sentinel\n");
        sb.append("var req = requestResponse.request();\n");

        String path = entry.getApiPath();
        String domain = entry.getDomain();
        String method = entry.getHttpMethod();

        sb.append("return ");

        // Path filter
        sb.append("req.url().contains(\"").append(escapeJava(path)).append("\")");

        // Domain filter
        if (domain != null && !domain.isEmpty()) {
            sb.append("\n    && req.headerValue(\"Host\").contains(\"")
              .append(escapeJava(domain)).append("\")");
        }

        // Method filter (only if a single specific method)
        if (method != null && !method.isEmpty() && !method.contains("/")) {
            sb.append("\n    && req.method().equals(\"").append(escapeJava(method)).append("\")");
        }

        sb.append(";");
        return sb.toString();
    }

    /**
     * Generate a Bambda filter expression for multiple API entries (OR combination).
     */
    public static String generateBatch(List<ApiEntry> entries) {
        if (entries.isEmpty()) return "// No APIs selected\nreturn false;";
        if (entries.size() == 1) return generate(entries.get(0));

        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by API Sentinel (").append(entries.size()).append(" APIs)\n");
        sb.append("var req = requestResponse.request();\n");
        sb.append("var url = req.url();\n");

        // Check if all entries share the same domain
        String commonDomain = entries.get(0).getDomain();
        boolean sameDomain = commonDomain != null && !commonDomain.isEmpty()
            && entries.stream().allMatch(e -> commonDomain.equals(e.getDomain()));

        sb.append("return ");

        if (sameDomain) {
            sb.append("req.headerValue(\"Host\").contains(\"")
              .append(escapeJava(commonDomain)).append("\")\n    && (");
        } else {
            sb.append("(");
        }

        for (int i = 0; i < entries.size(); i++) {
            ApiEntry e = entries.get(i);
            if (i > 0) sb.append("\n    || ");
            sb.append("url.contains(\"").append(escapeJava(e.getApiPath())).append("\")");
        }

        sb.append(");");
        return sb.toString();
    }

    private static String escapeJava(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }
}
