package com.flechazo.apisentinel.detection;

import com.flechazo.apisentinel.logging.LeveledLogger;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Identifies WAF block/challenge pages among payload responses, so a blocked
 * payload is reported as "inconclusive" instead of being misread as "safe"
 * (false negative) or as a real anomaly triggered by the block page itself
 * (false positive).
 *
 * Scoring model distilled from bughunter's tools/waf_response_analyzer.py
 * (shuvonsec/claude-bug-bounty, MIT License — see docs/THIRD-PARTY.md),
 * trimmed for internal-API testing: only passive signals are kept (vendor
 * signatures, block-page keywords, challenge pages, log IDs, edge latency).
 * The active block-baseline calibration signals (length/SHA256 comparison)
 * are intentionally NOT ported — they require firing known-malicious probes
 * at the target, which is inappropriate here.
 *
 * Thresholds: score &gt;= 60 → BLOCKED, 30-59 → NEEDS_REVIEW, &lt; 30 → PASSED
 * (treated as a genuine backend response).
 *
 * Known limitation: signatures cover 12 mainstream vendors; domestic WAFs
 * (AliYunDun, SafeLine, etc.) are not covered yet — see docs/THIRD-PARTY.md.
 */
/** WAF 检测器——12 厂商拦截页签名评分（≥60 拦截/30-59 待确认）。 */
public class WafDetector {

    /** Score at or above which the response is confidently a WAF block page. */
    public static final int THRESHOLD_BLOCKED = 60;
    /** Score at or above which the response may be a WAF page (needs review). */
    public static final int THRESHOLD_REVIEW = 30;

    /** Detection outcome for a single response. */
    public record WafDetectionResult(String vendor, int score, String detail) {
        public boolean isBlocked() {
            return score >= THRESHOLD_BLOCKED;
        }

        public boolean isSuspected() {
            return score >= THRESHOLD_REVIEW;
        }
    }

    private final LeveledLogger logger;

    // --- Vendor signature database (12 vendors, body + header patterns) ---
    private record Vendor(String name, Pattern[] body, Pattern[] header) {}

    private static final Vendor[] VENDORS = {
        vendor("cloudflare",
            new String[]{"cf-challenge-form", "Just a moment\\.\\.\\.",
                "Attention Required! \\| Cloudflare", "Sorry, you have been blocked",
                "Cloudflare Ray ID:", "Error 1020", "cdn-cgi/challenge-platform", "__cf_chl_tk"},
            new String[]{"cf-ray", "__cfduid", "__cf_bm", "cf-cache-status"}),
        vendor("aws-waf",
            new String[]{"<AccessDenied>", "Request blocked.*AWS", "Generated by cloudfront",
                "<TITLE>ERROR: The request could not be satisfied"},
            new String[]{"x-amzn-requestid", "x-amzn-trace-id", "x-amz-cf-id"}),
        vendor("imperva",
            new String[]{"_Incapsula_Resource", "incident ID:", "subject=WAF Block",
                "iframe.*incident_id", "visid_incap"},
            new String[]{"incap_ses", "visid_incap", "x-cdn: imperva", "x-iinfo"}),
        vendor("akamai",
            new String[]{"AkamaiGHost", "Reference #[0-9]", "ak-bm-",
                "Access Denied.*You don.t have permission"},
            new String[]{"akamai-x-", "akamaighost", "x-akamai"}),
        vendor("f5-bigip",
            new String[]{"The requested URL was rejected", "Please consult with your administrator",
                "[Ss]upport ID:.*[0-9]{10}", "support_id=[0-9]+"},
            new String[]{"TS[0-9a-f]{6,}"}),
        vendor("modsecurity",
            new String[]{"mod_security", "ModSecurity", "Not Acceptable!", "NAXSI"},
            new String[]{}),
        vendor("sucuri",
            new String[]{"Sucuri WebSite Firewall", "Access Denied - Sucuri", "Block reason:"},
            new String[]{"x-sucuri-id"}),
        vendor("fortiweb",
            new String[]{"Powered by Fortinet", "Attack ID:.*[0-9]", "FortiWeb"},
            new String[]{}),
        vendor("barracuda",
            new String[]{"Barracuda.*blocked", "BNI__BARRACUDA", "BNWeb"},
            new String[]{"barra_counter_session"}),
        vendor("wallarm",
            new String[]{"nginx-wallarm", "Wallarm"},
            new String[]{}),
        vendor("360-waf",
            new String[]{"360WebSafe", "wangzhan\\.360\\.cn"},
            new String[]{}),
        vendor("wordfence",
            new String[]{"Generated by Wordfence", "Wordfence.*blocked"},
            new String[]{})
    };

    // --- Generic block-page signals ---
    private static final Pattern BLOCK_TITLE = Pattern.compile(
        "(?i)(access denied|request rejected|blocked|forbidden|attention required|"
            + "403 forbidden|security violation|not acceptable)");

    private static final Pattern CHALLENGE_SIGNAL = Pattern.compile(
        "(?i)(cf-challenge-form|Just a moment\\.\\.\\.|checking your browser|"
            + "please enable javascript|cdn-cgi/challenge-platform)");

    private static final Pattern GENERIC_LOG_ID = Pattern.compile(
        "(?i)(?:log|trace|event|request|error|ref(?:erence)?|incident|support)"
            + "\\s*(?:id|number|#)[:\\s#]+([a-zA-Z0-9_\\-]{6,40})");

    public WafDetector(LeveledLogger logger) {
        this.logger = logger;
    }

    private static Vendor vendor(String name, String[] bodyPatterns, String[] headerPatterns) {
        Pattern[] body = new Pattern[bodyPatterns.length];
        for (int i = 0; i < bodyPatterns.length; i++) {
            body[i] = Pattern.compile(bodyPatterns[i], Pattern.CASE_INSENSITIVE | Pattern.DOTALL);
        }
        Pattern[] header = new Pattern[headerPatterns.length];
        for (int i = 0; i < headerPatterns.length; i++) {
            header[i] = Pattern.compile(headerPatterns[i], Pattern.CASE_INSENSITIVE);
        }
        return new Vendor(name, body, header);
    }

    /**
     * Analyze a raw HTTP response (headers + body) for WAF fingerprints.
     *
     * @param rawResponse    full raw HTTP response text (may be null/empty)
     * @param statusCode     response status code (informational for detail text)
     * @param responseTimeMs response latency; very fast responses (&lt;80ms) are
     *                       a weak edge-CDN/WAF signal
     */
    public WafDetectionResult detect(String rawResponse, int statusCode, long responseTimeMs) {
        if (rawResponse == null || rawResponse.isEmpty()) {
            return new WafDetectionResult(null, 0, "empty response");
        }

        String headers = rawResponse;
        String body = "";
        int sep = rawResponse.indexOf("\r\n\r\n");
        if (sep >= 0) {
            headers = rawResponse.substring(0, sep);
            body = rawResponse.substring(sep + 4);
        } else {
            int sepLf = rawResponse.indexOf("\n\n");
            if (sepLf >= 0) {
                headers = rawResponse.substring(0, sepLf);
                body = rawResponse.substring(sepLf + 2);
            }
        }

        int score = 0;
        List<String> signals = new ArrayList<>();
        String vendor = null;

        // 1. Vendor signature match: body first, then headers (+60).
        for (Vendor v : VENDORS) {
            boolean hit = false;
            for (Pattern p : v.body()) {
                if (p.matcher(body).find()) { hit = true; break; }
            }
            if (!hit) {
                for (Pattern p : v.header()) {
                    if (p.matcher(headers).find()) { hit = true; break; }
                }
            }
            if (hit) {
                vendor = v.name();
                score += 60;
                signals.add("vendor_match=" + v.name());
                break; // first matching vendor wins
            }
        }

        // 2. Block-page title keywords in the top of the body (+30).
        String bodyTop = body.length() > 4096 ? body.substring(0, 4096) : body;
        if (BLOCK_TITLE.matcher(bodyTop).find()) {
            score += 30;
            signals.add("block_title");
        }

        // 3. JS challenge / browser-check page (+30).
        String challengeWindow = body.length() > 8192 ? body.substring(0, 8192) : body;
        if (CHALLENGE_SIGNAL.matcher(challengeWindow).find()) {
            score += 30;
            signals.add("challenge");
        }

        // 4. Generic WAF log/incident/reference ID (+25).
        Matcher logId = GENERIC_LOG_ID.matcher(body);
        if (logId.find()) {
            score += 25;
            signals.add("log_id=" + logId.group(1));
        }

        // 5. Very fast response — weak CDN/WAF edge signal (+10).
        if (responseTimeMs > 0 && responseTimeMs < 80) {
            score += 10;
            signals.add("fast_response");
        }

        score = Math.min(score, 100);
        String detail = "status=" + statusCode
            + (signals.isEmpty() ? " no_waf_signal" : " " + String.join(",", signals));
        if (score >= THRESHOLD_REVIEW && logger != null) {
            logger.info("[WAF] suspected block page: " + detail);
        }
        return new WafDetectionResult(vendor, score, detail);
    }
}
